#!/bin/bash

unamestr=`uname`
ext="so"

if [[ "$unamestr" == 'Darwin' ]]; then
  ext="dylib"
fi

if ! which llvm-config > /dev/null 2>/dev/null; then
  echo "Error, llvm-config not in path." 1>&2
  exit 1
fi

if ! which kleenet > /dev/null 2>/dev/null; then
  echo "Error, kleenet not in path." 1>&2
  exit 1
fi

$(llvm-config --bindir)/opt -load $(dirname "$(which kleenet)")/../lib/prefix-symbols.$ext --llvm-prefix-symbols $@
